name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev execstack libstdc++6 ant
        pip3 install --user --upgrade buildozer
        export PATH=$PATH:~/.local/bin
        buildozer android clean
        buildozer android debug
    - uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
